# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'material property' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for material property

pod 'Appirater'

# Firebase

Pod 'Firebase/Core'
Pod 'Firebase/Auth'
Pod 'Firebase/Database'
Pod 'Firebase/Analytics'
Pod 'Firebase/Crashlytics'


end
